[project]
name = 'Tokenized-Real-Estate-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.property-token]
path = 'contracts/property-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.rental-income-distribution]
path = 'contracts/rental-income-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
